#install.packages("R.utils")
library(tidyverse)
library(rvest)
base_url <- "https://www.data.gouv.fr/fr/datasets/base-de-donnees-accidents-corporels-de-la-circulation/"
data_path <- "./data/"
already_downloaded <- TRUE

if (!already_downloaded) {
  page <- read_html(base_url)
  
  links <- page %>% html_nodes(".certified  a") %>%
    html_attr("href") %>% keep(~stringr::str_detect(., "pdf|csv"))
  
  dests <- links %>% basename() %>% stringr::str_c(data_path, .)
  walk2(links, dests, curl::curl_download)
  fs::dir_ls(data_path, glob = "*.csv") %>% R.utils::gzip()
  bad_files <- fs::dir_ls(data_path, glob = "*-*.csv.gz")
  fs::file_move(bad_files, bad_files %>% str_replace("-","_"))
}

col_types <- cols(.default = col_character(),
                  jour = col_integer(),
                  mois = col_integer(),
                  an = col_integer(),
                  lat = col_double(),
                  long = col_double(),
                  nbv = col_integer(),
                  pr1 = col_double(),
                  lartpc = col_double(),
                  larrout = col_double(),
                  occutc = col_integer(),
                  an_nais = col_integer()
)



if (!already_downloaded) {
  bad_file <- "./data//caracteristiques_2009.csv.gz"
  issue <- read_delim(bad_file,
                      delim = "\t",
                      col_types = col_types,
                      na = "-"
  )
  file.rename(bad_file, sprintf("%s_old", bad_file))
  write_csv(issue, bad_file)
}

years <- 2005:2017

dbs <- c("vehicules", "usagers", "lieux", "caracteristiques")

load_csv_accidents_year <- function(name, year, data_path) {
  filename <- sprintf("%s/%s_%4i.csv.gz", data_path, name, year)
  print(filename)
 tmp <- read_csv(filename,
          col_types = col_types,
          na = "-",
          locale = locale(encoding = "UTF-8")
          )
}

load_csv_accidents <- function(name, years, data_path) {
  map_df(years, ~ load_csv_accidents_year(name, ., data_path))
}

list2env(map(dbs, ~ load_csv_accidents(., years, data_path)) %>%
           set_names(dbs),
         .GlobalEnv)

caracteristiques <- caracteristiques %>%
  separate(hrmn, c("hr", "mn"), sep = -2, convert = FALSE) %>%
  mutate(date = stringr::str_c("20",
                               if_else(an<10,"0",""),
                               an,"-",mois,"-",jour,
                               " ",if_else(hr=="","0",hr),
                               ":",mn),
         date = lubridate::ymd_hm(date)) %>%
  select(-an, -mois, -jour, -hr, -mn) %>%
  select(Num_Acc, date, everything()) %>%
  mutate(lum = forcats::fct_recode(lum,
                                   NULL = "0",
                                   NULL = "",
                                   "Plein jour" = "1",
                                   "Crépuscule ou aube" = "2",
                                   "Nuit sans éclairage public" = "3",
                                   "Nuit avec éclairage public non allumé" = "4",
                                   "Nuit avec éclairage public allumé" = "5"),
         agg = forcats::fct_recode(agg,
                                   NULL = "0",
                                   NULL = "",
                                   "Hors agglomération" = "1",
                                   "En agglomération" = "2"),
         int = forcats::fct_recode(int,
                                   NULL = "0",
                                   NULL = "",
                                   "Hors intersection" = "1",
                                   "Intersection en X" = "2",
                                   "Intersection en T" = "3",
                                   "Intersection en Y" = "4",
                                   "Intersection à plus de 4 branches" = "5",
                                   "Giratoire" = "6",
                                   "Place" = "7",
                                   "Passage à niveau" =  "8",
                                   "Autre intersection" = "9"),
         atm = forcats::fct_recode(atm,
                                   NULL = "0",
                                   NULL = "",
                                   "Normale" = "1",
                                   "Pluie légère" = "2",
                                   "Pluie forte" = "3",
                                   "Neige - grêle" = "4",
                                   "Brouillard - fumée" = "5",
                                   "Vent fort - tempête" = "6",
                                   "Temps éblouissant" = "7",
                                   "Temps couvert" = "8",
                                   "Autre" = "9"),
         col = forcats::fct_recode(col,
                                   NULL = "0",
                                   NULL = "",
                                   "Deux véhicules - frontale" = "1",
                                   "Deux véhicules – par l’arrière" = "2",
                                   "Deux véhicules – par le coté" = "3",
                                   "Trois véhicules et plus – en chaîne" = "4",
                                   "Trois véhicules et plus - collisions multiples" = "5",
                                   "Autre collision" = "6",
                                   "Sans collision" = "7"),
         gps = forcats::fct_recode(gps,
                                   NULL = "0",
                                   NULL = "",
                                   "Métropole" = "M",
                                   "Antilles (Martinique ou Guadeloupe)" = "A",
                                   "Guyane" = "G",
                                   "Réunion"= "R",
                                   "Mayotte" = "Y",
                                   "St Pierre et Miquelon" = "S",
                                   "Polynésie française" = "P",
                                   "Wallis et Futuna" = "W",
                                   "Nouvelle Calédonie" = "C",
                                   "Terres austr. et antarct. Françaises" = "T"),
         lat = lat/1e5,
         long = long/1e5
  )

lieux <- lieux %>%
  mutate(
    catr = forcats::fct_recode(catr,
                               NULL = "0",
                               NULL = "",
                               "Autoroute" = "1",
                               "Route Nationale" = "2",
                               "Route Départementale" = "3",
                               "Voie Communale" = "4",
                               "Hors réseau public" = "5",
                               "Parc de stationnement ouvert à la circulation publique" = "6",
                               "Autre" = "9"),
    circ = forcats::fct_recode(circ,
                               NULL = "0",
                               NULL = "",
                               "A sens unique" = "1",
                               "Bidirectionnelle" = "2",
                               "A chaussées séparées" = "3",
                               "Avec voies d’affectation variable" = "4"),
    vosp = forcats::fct_recode(vosp,
                               NULL = "0",
                               NULL = "",
                               "Piste cyclable" = "1",
                               "Banque cyclable" = "2",
                               "Voie réservée" = "3"),
    prof = forcats::fct_recode(prof,
                               NULL = "0",
                               NULL = "",
                               "Plat" = "1",
                               "Pente" = "2",
                               "Sommet de côte" = "3",
                               "Bas de côte" = "4"),
    plan = forcats::fct_recode(plan,
                               NULL = "0",
                               NULL = "",
                               "Partie rectiligne" = "1",
                               "En courbe à gauche" = "2",
                               "En courbe à droite" = "3",
                               "En « S »" = "4"),
    surf = forcats::fct_recode(surf,
                               NULL = "0",
                               NULL = "",
                               "normale" = "1",
                               "mouillée" = "2",
                               "flaques" = "3",
                               "inondée" = "4",
                               "enneigée" = "5",
                               "boue" = "6",
                               "verglacée" = "7",
                               "corps gras - huile" = "8",
                               "autre" = "9"),
    infra = forcats::fct_recode(infra,
                                NULL = "0",
                                NULL = "",
                                "Souterrain - tunnel" = "1",
                                "Pont - autopont" = "2",
                                "Bretelle d’échangeur ou de raccordement" = "3",
                                "Voie ferrée" = "4",
                                "Carrefour aménagé" = "5",
                                "Zone piétonne" = "6",
                                "Zone de péage" = "7"),
    situ = forcats::fct_recode(situ,
                               NULL = "0",
                               NULL = "",
                               "Sur chaussée" = "1",
                               "Sur bande d’arrêt d’urgence" = "2",
                               "Sur accotement" = "3",
                               "Sur trottoir" = "4",
                               "Sur piste cyclable" = "5")
  )

vehicules <- vehicules %>%
  mutate(senc = forcats::fct_recode(senc,
                                    NULL = "0",
                                    NULL = "",
                                    "PK ou PR ou numéro d’adresse postale croissant" = "1",
                                    "PK ou PR ou numéro d’adresse postale décroissant" = "2"),
         catv = forcats::fct_recode(catv,
                                    NULL = "00",
                                    NULL = "",
                                    "Bicyclette" = "01",
                                    "Cyclomoteur <50cm3" = "02",
                                    "Voiturette (Quadricycle à moteur carrossé) (anciennement voiturette ou tricycle à moteur)" = "03",
                                    "Référence plus utilisée depuis 2006 (scooter immatriculé)" = "04",
                                    "Référence plus utilisée depuis 2006 (motocyclette)" = "05",
                                    "Référence plus utilisée depuis 2006 (side-car)" = "06",
                                    "VL seul" = "07",
                                    "Catégorie plus utilisée (VL + caravane)" = "08",
                                    "Catégorie plus utilisée (VL + remorque)" = "09" ,
                                    "VU seul 1,5T <= PTAC <= 3,5T avec ou sans remorque (anciennement VU seul 1,5T <= PTAC <= 3,5T)" = "10",
                                    "Référence plus utilisée depuis 2006 (VU (10) + caravane)" = "11",
                                    "Référence plus utilisée depuis 2006 (VU (10) + remorque)" = "12",
                                    "PL seul 3,5T <PTCA <= 7,5T" = "13",
                                    "PL seul > 7,5T" = "14",
                                    "PL > 3,5T + remorque" = "15",
                                    "Tracteur routier seul" = "16",
                                    "Tracteur routier + semi-remorque" = "17",
                                    "Référence plus utilisée depuis 2006 (transport en commun)" = "18",
                                    "Référence plus utilisée depuis 2006 (tramway)" = "19",
                                    "Engin spécial" = "20",
                                    "Tracteur agricole" = "21",
                                    "Scooter < 50 cm3" = "30",
                                    "Motocyclette > 50 cm et <= 125 cm" = "31",
                                    "Scooter > 50 cm et <= 125 cm" = "32",
                                    "Motocyclette > 125 cm" = "33",
                                    "Scooter > 125 cm" = "34",
                                    "Quad léger <= 50 cm (Quadricycle à moteur non carrossé)" = "35",
                                    "Quad lourd > 50 cm (Quadricycle à moteur non carrossé)" = "36",
                                    "Autobus" = "37",
                                    "Autocar" = "38",
                                    "Train" = "39",
                                    "Tramway" = "40",
                                    "Autre véhicule" = "99"),
         obs = forcats::fct_recode(obs,
                                   NULL = "00",
                                   NULL = "",
                                   "Véhicule en stationnement" = "01",
                                   "Arbre" = "02",
                                   "Glissière métallique" = "03",
                                   "Glissière béton" = "04",
                                   "Autre glissière" = "05",
                                   "Bâtiment, mur, pile de pont" = "06",
                                   "Support de signalisation verticale ou poste d’appel d’urgence" = "07",
                                   "Poteau" = "08",
                                   "Mobilier urbain" = "09",
                                   "Parapet" = "10",
                                   "Ilot, refuge, borne haute" = "11",
                                   "Bordure de trottoir" = "12",
                                   "Fossé, talus, paroi rocheuse" = "13",
                                   "Autre obstacle fixe sur chaussée" = "14", 
                                   "Autre obstacle fixe sur trottoir ou accotement" = "15",
                                   "Sortie de chaussée sans obstacle" = "16"),
         obsm = forcats::fct_recode(obsm,
                                    NULL = "0",
                                    NULL = "",
                                    "Piéton" = "1",
                                    "Véhicule" = "2",
                                    "Véhicule sur rail" = "4",
                                    "Animal domestique" = "5",
                                    "Animal sauvage" = "6",
                                    "Autre" = "9"),
         choc = forcats::fct_recode(choc,
                                    NULL = "0",
                                    NULL = "",
                                    "Avant" = "1",
                                    "Avant droit" = "2",
                                    "Avant gauche" = "3",
                                    "Arrière" = "4",
                                    "Arrière droit" = "5",
                                    "Arrière gauche" = "6",
                                    "Côté droit" = "7",
                                    "Côté gauche" = "8",
                                    "Chocs multiples (tonneaux)" = "9"),
         manv = forcats::fct_recode(manv,
                                    NULL = "00",
                                    NULL = "",
                                    "Sans changement de direction" = "01",
                                    "Même sens, même file" = "02",
                                    "Entre 2 files" = "03",
                                    "En marche arrière" = "04",
                                    "A contresens" = "05",
                                    "En franchissant le terre-plein central" = "06",
                                    "Dans le couloir bus, dans le même sens" = "07",
                                    "Dans le couloir bus, dans le sens inverse" = "08",
                                    "En s’insérant" = "09",
                                    "En faisant demi-tour sur la chaussée" = "10",
                                    "Changeant de file à gauche" = "11",
                                    "Changeant de file à droite" = "12",
                                    "Déporté à gauche" = "13",
                                    "Déporté à droite" = "14",
                                    "Tournant à gauche" = "15",
                                    "Tournant à droite" = "16",
                                    "Dépassant à gauche" = "17",
                                    "Dépassant à droite" = "18",
                                    "Traversant la chaussée" = "19",
                                    "Manœuvre de stationnement" = "20",
                                    "Manœuvre d’évitement" = "21",
                                    "Ouverture de porte" = "22",
                                    "Arrêté (hors stationnement)" = "23",
                                    "En stationnement (avec occupants)" = "24"
         )
         
  )

usagers <- usagers %>%
  mutate(catu = forcats::fct_recode(catu,
                                    NULL = "0",
                                    NULL = "",
                                    "Conducteur" = "1",
                                    "Passager" = "2",
                                    "Piéton" = "3",
                                    "Piéton en roller ou en trottinette" = "4"),
         grav = forcats::fct_recode(grav,
                                    NULL = "0",
                                    NULL = "",
                                    "Indemne" = "1",
                                    "Tué" = "2",
                                    "Blessé hospitalisé" = "3",
                                    "Blessé léger" = "4") %>%
           forcats::fct_relevel("Indemne", after = Inf),
         sexe = forcats::fct_recode(sexe,
                                    NULL = "0",
                                    NULL = "",
                                    "Masculin" = "1",
                                    "Féminin" = "2"),
         trajet = forcats::fct_recode(trajet,
                                      NULL = "0",
                                      NULL = "",
                                      "Domicile – travail" = "1",
                                      "Domicile – école" = "2",
                                      "Courses – achats" = "3",
                                      "Utilisation professionnelle" = "4",
                                      "Promenade – loisirs" = "5",
                                      "Autre" = "9"),
         locp = forcats::fct_recode(locp,
                                    NULL = "0",
                                    NULL = "",
                                    "Sur chaussée à + 50 m du passage piéton" = "1",
                                    "Sur chaussée à – 50 m du passage piéton" = "2",
                                    "Sur passage piéton sans signalisation lumineuse" = "3",
                                    "Sur passage piéton avec signalisation lumineuse" = "4",
                                    "Sur trottoir" = "5",
                                    "Sur accotement" = "6",
                                    "Sur refuge ou BAU" = "7",
                                    "Sur contre allée" = "8"),
         actp = forcats::fct_recode(actp,
                                    NULL = "0",
                                    NULL = "",
                                    "Sens véhicule heurtant" = "1",
                                    "Sens inverse du véhicule" = "2",
                                    "Traversant" = "3",
                                    "Masqué" = "4",
                                    "Jouant – courant" = "5",
                                    "Avec animal" = "6",
                                    "Autre" = "9"),
         etatp = forcats::fct_recode(etatp,
                                     NULL = "",
                                     NULL = "0",
                                     "Seul" = "1",
                                     "Accompagné" = "2",
                                     "En groupe" = "3")) %>%
  separate(secu, c("secup", "secuu"), 1) %>% 
  mutate(secup = forcats::fct_recode(secup,
                                     NULL = "0",
                                     NULL = "",
                                     "Ceinture" = "1",
                                     "Casque" = "2",
                                     "Dispositif enfants" = "3",
                                     "Equipement réfléchissant" = "4",
                                     "Autre" = "9"),
         secuu = forcats::fct_recode(secuu,
                                     NULL= "0",
                                     NULL = "",
                                     "Oui" = "1",
                                     "Non" = "2",
                                     "Non déterminable" = "3")
         )
